### ISSUE TITLE
Is there a tutorial?/有相关文档吗？

### ISSUE THREAD

**Issue by VoldemortGin** [Panmax/kddz#1]
Hi Author, thank you for your excellent work. It would be very nice if you can provider a simple tutorial  shows how to start from beginning.
作者你好，谢谢你出色的作品。如果能提供一份简易文档（列出相关包的版本号，以及如何从零配置）就更好了。

**Comment by Panmax** [comment]
抱歉，这个项目是大学时候写的，工作后才开源的，当时不太注重工程化，有些东西也没有保留下来。

有需求的话可以使用重写后的 SaaS 版本：https://bossku.cn
