### ISSUE TITLE
请问有相关依赖文件吗？比如requirements.txt

### ISSUE THREAD

**Issue by AngelLiang** [Panmax/kddz#2]
目前不知道您项目的jdango版本是多少？无法进行测试部署。

**Comment by 2466768880** [comment]
可以联系我，qq 54430978

**Comment by 2466768880** [comment]
可以联系我，私聊

**Comment by Panmax** [comment]
抱歉，这个项目是大学时候写的，工作后才开源的，当时不太注重工程化，有些东西也没有保留下来。

有需求的话可以使用重写后的 SaaS 版本：https://bossku.cn
